/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dorvonirdrbsaqvxbymt"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvcnZvbmlyZHJic2FxdnhieW10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNDEwNTksImV4cCI6MjA4MzYxNzA1OX0.RI_iMsZ-K-wW9DH1Cc6IPRsYe2rXJdmYzFLlDk3uIz0"